[package]
name = "rust"
version = "0.1.0"
authors = ["Bibek Pandey <bibekp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicode-segmentation = "1.6.0"
rayon = "1.1"
maplit = "1.0.2"